version: '4.0'

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "2222:2222"
    depends_on:
      - asyncredis

  asyncredis:
    image: redis:latest
    container_name: asyncredis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
